version: '3'
networks:
  app-network:
    driver: bridge
  app-custom-nextwork:
    external:
      name: socket_server
services:
  blogv3:
    # 指定以当前目录下的Dockerfile文件打包成镜像
    build:
      context: .
      dockerfile: dockerfile.node
    container_name: blogv3
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - app-network
      - app-custom-nextwork
    depends_on:
      - db
    mem_limit: 2G
    mem_reservation: 128M
    cpus: 0.5
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 128M
  db:
    build:
      context: .
      dockerfile: dockerfile.mysql
    container_name: dbv3
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=175947
      - MYSQL_USER=vanweiping
      - MYSQL_PASS=175947
      - MYSQL_DATABASE=db_myblog
      - TZ=Asia/Shanghai # 设置时区
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf/my.conf:/etc/my.conf
      - ./mysql/logs:/mysql/logs
      - ./mysql/init:/docker-entrypoint-initdb.d/
      # 备份目录
      - /root/sql_back_myblog:/home/back
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-network
      - app-custom-nextwork
